# https://pre-commit.com/hooks.html

ci:
  autoupdate_schedule: quarterly
  skip:
    - copyright
    - ripsecrets
    - jsonschema-validator

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-ast
        exclude: |-
          (?x)^(
            c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/{{cookiecutter.package}}/models/c2cgeoform_demo\.py
            |c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/acceptance_tests/excavation_test\.py
            |c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/acceptance_tests/conftest\.py
          )$
      - id: debug-statements
        exclude: |-
          (?x)^(
            c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/{{cookiecutter.package}}/models/c2cgeoform_demo\.py
            |c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/acceptance_tests/excavation_test\.py
            |c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/acceptance_tests/conftest\.py
          )$
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/sbrunner/hooks
    rev: 0.5.0
    hooks:
      - id: copyright
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        exclude: |-
          (?x)^(
            c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/{{cookiecutter.package}}/data/osm-lausanne-bus-stops\.geojson
            |.*\.po(_tmpl)?
            |poetry\.lock
            |c2cgeoform/static/package-lock\.json
          )$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.3.3 # npm
          - prettier-plugin-sh@0.14.0 # npm
          - prettier-plugin-toml@2.0.2 # npm
          - '@prettier/plugin-xml@0.12.0' # npm
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.1
    hooks:
      - id: check-github-workflows
      - id: check-jsonschema
        name: Check GitHub Workflows set timeout-minutes
        files: ^\.github/workflows/[^/]+$
        types:
          - yaml
        args:
          - --builtin-schema
          - github-workflows-require-timeout
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.7
    hooks:
      - id: ripsecrets
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        exclude: |-
          (?x)^(
            c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/{{cookiecutter.package}}/models/c2cgeoform_demo\.py
            |c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/acceptance_tests/excavation_test\.py
            |c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/acceptance_tests/conftest\.py
          )$
  - repo: https://github.com/sbrunner/jsonschema-validator
    rev: 0.1.0
    hooks:
      - id: jsonschema-validator
        files: ^ci/config\.yaml$
