# https://pre-commit.com/hooks.html

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-ast
        exclude: |-
          (?x)^(
            c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/{{cookiecutter.package}}/models/c2cgeoform_demo\.py
            |c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/acceptance_tests/excavation_test\.py
            |c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/acceptance_tests/conftest\.py
          )$
      - id: debug-statements
        exclude: |-
          (?x)^(
            c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/{{cookiecutter.package}}/models/c2cgeoform_demo\.py
            |c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/acceptance_tests/excavation_test\.py
            |c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/acceptance_tests/conftest\.py
          )$
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/sbrunner/hooks
    rev: 1.6.0
    hooks:
      - id: copyright
      - id: workflows-require-timeout
      - id: poetry2-lock
        additional_dependencies:
          - poetry==2.1.3 # pypi
      - id: canonicalize
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: |-
          (?x)^(
            c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/{{cookiecutter.package}}/data/osm-lausanne-bus-stops\.geojson
            |.*\.po(_tmpl)?
            |poetry\.lock
            |c2cgeoform/static/package-lock\.json
          )$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.6.2 # npm
          - prettier-plugin-sh@0.18.0 # npm
          - prettier-plugin-toml@2.0.6 # npm
          - '@prettier/plugin-xml@0.12.0' # npm
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.2
    hooks:
      - id: check-github-workflows
      - id: check-jsonschema
        name: Check GitHub Workflows set timeout-minutes
        files: ^\.github/workflows/[^/]+$
        types:
          - yaml
        args:
          - --builtin-schema
          - github-workflows-require-timeout
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.9
    hooks:
      - id: ripsecrets
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff-format
        args:
          - --line-length=110
        exclude: |-
          (?x)^(
            c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/acceptance_tests/.*
            |c2cgeoform/scaffolds/c2cgeoform/{{cookiecutter.project}}/{{cookiecutter.package}}/models/c2cgeoform_demo\.py
          )$
  - repo: https://github.com/PyCQA/prospector
    rev: v1.17.3
    hooks:
      - id: prospector
        args:
          - --profile=utils:pre-commit
          - --profile=.prospector.yaml
          - --die-on-tool-error
          - --output-format=pylint
        additional_dependencies:
          - prospector-profile-duplicated==1.10.5 # pypi
          - prospector-profile-utils==1.26.0 # pypi
          - pylint[spelling]==3.3.7 # pypi
          - ruff==0.12.7 # pypi
        exclude: |-
          (?x)(
            ^tests?/?
            |/tests?(/|$)
            |.*/tests(/|$)
            |(^|/)test_[_a-zA-Z0-9]+.py$
            |(^|/)[_a-zA-Z0-9]+_tests?.py$
            |(^|/)tests?.py$
            |/\{\{cookiecutter\.project\}\}/
          )
      - id: prospector
        args:
          - --die-on-tool-error
          - --output-format=pylint
          - --profile=utils:tests
          - --profile=utils:pre-commit
        additional_dependencies:
          - prospector-profile-utils==1.26.0 # pypi
        exclude: |-
          (?x)(
            /\{\{cookiecutter\.project\}\}/
          )
  - repo: https://github.com/sbrunner/jsonschema-validator
    rev: 1.0.0
    hooks:
      - id: jsonschema-validator
        files: ^\.github/publish\.yaml$
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.43.0
    hooks:
      - id: renovate-config-validator
  - repo: https://github.com/sbrunner/python-versions-hook
    rev: 1.1.2
    hooks:
      - id: python-versions
