inherits:
  - duplicated
  - utils:base
  - utils:no-design-checks
  - utils:c2cwsgiutils
  - utils:fix

ignore-paths:
  - c2cgeoform/scaffolds/c2cgeoform/

mypy:
  options:
    python-version: '3.11'

ruff:
  disable:
    - D101 # Missing docstring in public class
    - D102 # Missing docstring in public method
    - D107 # Missing docstring in `__init__`
    - ARG002 # Unused method argument
    - ARG005 # Unused lambda argument
  options:
    target-version: py311
