inherits:
  - duplicated

strictness: veryhigh
max-line-length: 110

ignore-paths:
  - c2cgeoform/scaffolds/c2cgeoform/+package+

mypy:
  run: true

mccabe:
  run: false

bandit:
  run: true
  options:
    config: .bandit.yaml

pyorama:
  run: true
