#!/bin/bash -ex

if [[ "${GITHUB_ACTIONS}" == "true" ]]; then
  if [[ "${GITHUB_REF}" =~ ^refs/tags/.* ]]; then
    # shellcheck disable=SC2001
    GIT_TAGS=$(echo "${GITHUB_REF}" | sed 's|^refs/tags/||g')
  fi
else
  GIT_TAGS=$(git tag --points-at HEAD)
fi

function deploy_pypi {
  rm -rf dist/*
  make compile-catalog
  VERSION=$1 python3 setup.py egg_info sdist bdist_wheel
  twine upload -r testpypi dist/*
}

# Deploy tags
for GIT_TAG in ${GIT_TAGS}; do
  deploy_pypi "${GIT_TAG}"
done
