# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.3.22/c2cciutils/schema.json

publish:
  docker:
    images: []
  pypi:
    versions:
      - version_tag
checks:
  required_workflows: false
  codespell: false
