name: Audit

on:
  schedule:
    - cron: "30 2 * * *"

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        branch:
          - "2.0"
          - "2.1"
    steps:
      # Remove Python packages with wrong version
      - run: sudo apt-get remove python3-debian python3-distro-info
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

          token: ${{ secrets.GOPASS_CI_GITHUB_TOKEN }}
      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}

      - run: python3 -m pip install --pre c2cciutils[audit]

      - name: Check .tool-versions file existence
        id: tool-versions
        uses: andstor/file-existence-action@v2
        with:
          files: .tool-versions
      - uses: asdf-vm/actions/install@v3
        if: steps.tool-versions.outputs.files_exists == 'true'
      - run: cat /tmp/python-build.*.log
        if: failure()
      - run: python --version

      - name: Snyk audit
        run: ~/.venv/bin/c2cciutils-audit --branch=${{ matrix.branch }}
      - name: Snyk audit
        run: ~/.venv/bin/c2cciutils-audit --branch=${{ matrix.branch }} || true
        if: failure()
        env:
          DEBUG: "*snyk*"
      - name: Update dpkg packages versions
        run: c2cciutils-docker-versions-update --branch=${{ matrix.branch }}
