---

name: Continuous integration

on:
  push:

jobs:
  main:
    name: Continuous integration
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    env:
      TX_USR: ${{ secrets.TX_USR }}
      TX_PWD: ${{ secrets.TX_PWD }}
      TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
      - name: Install packages
        run: sudo apt-get install -y gettext python3-virtualenv
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - name: Build
        run: make build
      - name: Lint
        run: make check
      - name: Tests
        run: make test
      - name: Docker compose logs
        if: always()
        run: |
          docker-compose logs
          docker-compose down -v --remove-orphans
      - name: Deploy PyPI
        if: >
          github.repository == 'camptocamp/c2cgeoform'
          && success()
          && (
            startsWith(github.ref, 'refs/tags/')
          )
        run: |
          sudo python3 -m pip install twine wheel
          scripts/deploy-pypi
