name: Continuous integration

on:
  push:

env:
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}

jobs:
  main:
    name: Continuous integration
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: sudo apt-get install -y gettext python3-virtualenv

      - uses: actions/setup-node@v3
        with:
          node-version: 10

      - name: Build
        run: make build

      - name: Lint
        run: make check

      - name: Tests
        run: make test

      - name: Docker compose logs
        run: |
          docker compose logs
          docker compose down -v --remove-orphans
        if: always()
      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: pypi
        if: env.HAS_SECRETS == 'HAS_SECRETS'

      - name: Install c2cciutils
        run: |
          echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
          python3 -m pip install --user --upgrade pip
          python3 -m pip install --user --requirement=ci/requirements.txt

      - run: pip install cryptography==3.4.8 pyOpenSSL==20.0.1
      - name: Publish
        run: c2cciutils-publish
        if: env.HAS_SECRETS == 'HAS_SECRETS'
      - run: git diff --exit-code --patch > /tmp/dpkg-versions.patch || true
        if: failure()
      - uses: actions/upload-artifact@v4
        with:
          name: Update dpkg versions list.patch
          path: /tmp/dpkg-versions.patch
          retention-days: 1
        if: failure()
